#61 strong typing
steroids/boilerplate-nest pull request #2
Opened 2024-11-25 06:03 UTC by Novtin

2024-11-28 09:42 UTC, vkoktashev commented on src/notifier/infrastructure/NotifierModule.ts
> -                    port: parseInt(process.env.MAIL_PORT, 10),
Лучше какое-то дефолтное значение определить

2024-11-28 09:43 UTC, vkoktashev commented on src/auth/infrastructure/AuthModule.ts
> +        const module = coreModule?.module(config);
не понял, для чего тут "?.", если ты дальше к module обращаешься через точку. В таком случае все равно всё сломается

2024-11-28 09:45 UTC, vkoktashev commented on src/base/infrastructure/filters/ValidationExceptionFilterCustom.ts
> +    async parseErrors(errors: any, contextLanguage: string): Promise<ErrorsCompositeObject> {
Добавляем строгую типизацию и прописываем any? 🌝

2024-11-28 09:46 UTC, vkoktashev commented on src/base/infrastructure/filters/ValidationExceptionFilterCustom.ts
> +    async parseErrors(errors: any, contextLanguage: string): Promise<ErrorsCompositeObject> {
Надо стероиды обновить в бойлерплейте, если там сейчас не последняя версия. Там сейчас есть чёткий интерфейс у ошибок

2024-11-28 09:47 UTC, vkoktashev commented on src/init/infrastructure/helpers/entitiesExporter.ts
> +function exportEnum(enumClass: any) {
Про any выше коммент оставил уже, тут то же самое

2024-12-02 09:51 UTC, perlexed commented
@vkoktashev @Novtin замечания, которые Влад оставлял, устранили? ни один тред не указан как resolved

2024-12-03 02:48 UTC, Novtin commented
> @vkoktashev @Novtin замечания, которые Влад оставлял, устранили? ни один тред не указан как resolved

Я исправил, что Влад написал, но он ещё не смотрел, видимо

2024-12-04 07:21 UTC, alexpryazhnikov requested changes
Ничего плохого в any типах не вижу, пусть лучше миграция будет плавной (any тоже тип).
Основная цель задачи правильно выводить типы из того же TypeORM и не сломать компиляцию TS.

2024-12-04 07:21 UTC, alexpryazhnikov commented on src/base/infrastructure/filters/ValidationExceptionFilterCustom.ts
> +            async (result: any, error: ValidationError): Promise<IErrorsCompositeObject> => {
Почему метод асинхронный? Тот же вопрос к функции переданной в reduce

2024-12-05 03:09 UTC, Novtin commented on src/base/infrastructure/filters/ValidationExceptionFilterCustom.ts
> +            async (result: any, error: ValidationError): Promise<IErrorsCompositeObject> => {
Это надо узнавать у автора

2024-12-13 14:54 UTC, vkoktashev commented on src/base/infrastructure/filters/ValidationExceptionFilterCustom.ts
> +            async (result: any, error: ValidationError): Promise<IErrorsCompositeObject> => {
Автор не в курсе🌚
Перетащил при рефактиронге аснхронность из предыдущей версии скорее всего и внимания не обратил

2024-12-13 14:56 UTC, vkoktashev approved these changes

2024-12-20 05:45 UTC, perlexed commented on src/init/infrastructure/helpers/entitiesExporter.ts
> +        .map((enumElement: {id: string, label: string,}) => ({
В случае записи параметров в одну строку, запятая в конце не нужна.

Если это автоматом проставилось, то нужно такие правила отключать.

2024-12-20 05:45 UTC, perlexed commented on src/init/infrastructure/helpers/entitiesExporter.ts
> +    const result: {[key: string] : {attributes: IFieldData[],},} = {};
То же замечание что и выше

2024-12-20 05:45 UTC, perlexed commented on src/notifier/infrastructure/NotifierModule.ts
> +                    port: parseInt(process.env.MAIL_PORT ?? '465', 10),
Дефолтное значение нужно вынести в именованную константу.

2024-12-20 05:45 UTC, perlexed commented on yarn.lock
Почему в PR по добавлению типизации обновляется версия core-библиотеки?

2024-12-20 05:45 UTC, perlexed commented on src/auth/infrastructure/AuthModule.ts
> +                ...(module.controllers ? module.controllers.filter(controller => controller !== BaseAuthController) : []),
```suggestion
                ...(module.controllers || []).filter(controller => controller !== BaseAuthController),
```

2025-01-09 03:16 UTC, Novtin commented on yarn.lock
@perlexed потому что https://github.com/steroids/boilerplate-nest/pull/2#discussion_r1861840386

2025-01-13 04:49 UTC, perlexed commented on .eslintrc
> +        ]
Почему решено эти правила включать на уровне проекта, а не на уровне steroidsjs/eslint?

2025-01-16 04:42 UTC, Novtin commented on .eslintrc
> +        ]
@perlexed  после мержей https://github.com/steroids/boilerplate-nest/pull/4 и https://github.com/steroids/eslint-config/pull/5 надо будет исправить .eslintrc в этом репозитории. Пока вернул как было

2025-01-16 05:15 UTC, perlexed reviewed
Замечания про запятые остались незакрытыми

2025-01-20 08:32 UTC, Novtin commented
@perlexed https://github.com/steroids/boilerplate-nest/pull/2#discussion_r1917699271

2025-01-20 09:59 UTC, perlexed commented
> @perlexed [#2 (comment)](https://github.com/steroids/boilerplate-nest/pull/2#discussion_r1917699271)

Прошу пояснения.

2025-01-21 07:38 UTC, Novtin commented
> > @perlexed [#2 (comment)](https://github.com/steroids/boilerplate-nest/pull/2#discussion_r1917699271)
> 
> Прошу пояснения.

В общем, я исправил

2025-01-22 06:32 UTC, perlexed approved these changes

2025-01-28 11:45 UTC, alexpryazhnikov approved these changes

2025-01-29 08:20 UTC, merged